### ISSUE TITLE
Issue setting up NAD AMP with HA

### ISSUE THREAD

**Issue by bmf7777** [Breina/nad_controller#1]
i'm getting the following error message when trying to setup NAD amp ... any ideas what i'm doing wrong ? i'm able to program it's internal web page

2024-02-28 04:59:37.942 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NAD 16-60 DSP for nad_controller
Traceback (most recent call last):
  File "/srv/homeassistant_3.11/lib/python3.11/site-packages/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/nad_controller/__init__.py", line 38, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by Breina** [comment]
Looks like a bug, haven't updated this integration to the latest HA version. Let me fix that for you.

**Comment by Breina** [comment]
Fixed in https://github.com/Breina/nad_controller/releases/tag/v0.1.0.
